cmake_minimum_required(VERSION 3.22)

get_filename_component(_engineSourceRoot "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
include("${_engineSourceRoot}/BuildTools/Init.cmake")

set(_interfacePath "${_engineSourceRoot}/BuildTools/cmake/ProjectInterface.json")
file(READ "${_interfacePath}" _interfaceJson)
string(JSON _schemaVersion GET "${_interfaceJson}" schema_version)
if(NOT _schemaVersion EQUAL 1)
	message(FATAL_ERROR "Unexpected project-interface schema: ${_schemaVersion}")
endif()

string(JSON _optionCount LENGTH "${_interfaceJson}" options)
string(JSON _stageCount LENGTH "${_interfaceJson}" stages)
string(JSON _helperCount LENGTH "${_interfaceJson}" helpers)
if(NOT _optionCount EQUAL 44 OR NOT _stageCount EQUAL 10 OR NOT _helperCount EQUAL 6)
	message(FATAL_ERROR "Unexpected project-interface shape: ${_optionCount} options, ${_stageCount} stages, ${_helperCount} helpers")
endif()

set(_manifestStages "")
math(EXPR _lastStageIndex "${_stageCount} - 1")
foreach(_stageIndex RANGE 0 ${_lastStageIndex})
	string(JSON _stageOrder GET "${_interfaceJson}" stages ${_stageIndex} order)
	string(JSON _stageName GET "${_interfaceJson}" stages ${_stageIndex} name)
	string(JSON _stageEntrypoint GET "${_interfaceJson}" stages ${_stageIndex} entrypoint)
	string(JSON _stageSource GET "${_interfaceJson}" stages ${_stageIndex} source)
	string(JSON _stageHooks LENGTH "${_interfaceJson}" stages ${_stageIndex} hooks)
	math(EXPR _expectedOrder "${_stageIndex} + 1")

	if(NOT _stageOrder EQUAL _expectedOrder)
		message(FATAL_ERROR "Non-contiguous project-interface stage order at ${_stageName}: ${_stageOrder}")
	endif()
	if(NOT _stageHooks EQUAL 2)
		message(FATAL_ERROR "Unexpected hook count for ${_stageName}: ${_stageHooks}")
	endif()
	string(JSON _preHook GET "${_interfaceJson}" stages ${_stageIndex} hooks 0)
	string(JSON _postHook GET "${_interfaceJson}" stages ${_stageIndex} hooks 1)
	if(NOT _preHook STREQUAL "Pre" OR NOT _postHook STREQUAL "Post")
		message(FATAL_ERROR "Unexpected hook surface for ${_stageName}: ${_preHook};${_postHook}")
	endif()
	if(NOT EXISTS "${_engineSourceRoot}/${_stageSource}")
		message(FATAL_ERROR "Missing project-interface stage source: ${_stageSource}")
	endif()
	if(NOT COMMAND ${_stageEntrypoint})
		message(FATAL_ERROR "Missing project-interface stage entrypoint ${_stageEntrypoint} for ${_stageName}")
	endif()
	list(APPEND _manifestStages "${_stageName}")
endforeach()
if(NOT "${_manifestStages}" STREQUAL "${FO_KNOWN_STAGES}")
	message(FATAL_ERROR "Project-interface stages differ from BuildTools/Init.cmake: manifest='${_manifestStages}', runtime='${FO_KNOWN_STAGES}'")
endif()

file(READ "${_engineSourceRoot}/BuildTools/cmake/stages/Init.cmake" _initStageSource)
math(EXPR _lastOptionIndex "${_optionCount} - 1")
foreach(_optionIndex RANGE 0 ${_lastOptionIndex})
	string(JSON _optionName GET "${_interfaceJson}" options ${_optionIndex} name)
	string(FIND "${_initStageSource}" "${_optionName}" _optionOffset)
	if(_optionOffset EQUAL -1)
		message(FATAL_ERROR "Project-interface option is not declared by the Init stage: ${_optionName}")
	endif()
endforeach()

math(EXPR _lastHelperIndex "${_helperCount} - 1")
foreach(_helperIndex RANGE 0 ${_lastHelperIndex})
	string(JSON _helperName GET "${_interfaceJson}" helpers ${_helperIndex} name)
	string(JSON _helperKind GET "${_interfaceJson}" helpers ${_helperIndex} kind)
	string(JSON _helperSource GET "${_interfaceJson}" helpers ${_helperIndex} source)
	set(_helperPath "${_engineSourceRoot}/${_helperSource}")
	if(NOT EXISTS "${_helperPath}")
		message(FATAL_ERROR "Missing project-interface helper source: ${_helperSource}")
	endif()
	file(READ "${_helperPath}" _helperSourceText)
	if(NOT _helperSourceText MATCHES "${_helperKind}\\(${_helperName}([ \\t\\r\\n)]|$)")
		message(FATAL_ERROR "Project-interface helper ${_helperName} is not declared in ${_helperSource}")
	endif()
endforeach()

if(COMMAND AddProjectLibraries)
	message(FATAL_ERROR "Undeclared AddProjectLibraries helper unexpectedly exists")
endif()
foreach(_libraryList IN ITEMS FO_COMMON_LIBS FO_SERVER_LIBS FO_CLIENT_LIBS FO_BAKER_LIBS FO_TESTING_LIBS)
	if(NOT DEFINED ${_libraryList})
		message(FATAL_ERROR "Missing revision-pinned project library list: ${_libraryList}")
	endif()
endforeach()
if(DEFINED FO_MAPPER_LIBS)
	message(FATAL_ERROR "Undocumented mapper-only library list unexpectedly exists")
endif()

message(STATUS "Validated documented FOnline project interface against current CMake declarations: ${_optionCount} options, ${_stageCount} stages, ${_helperCount} helpers")
