#!/usr/bin/env python3
"""Generate the static interop shim lookup table for the embedded Mono runtime.

CoreLib reaches the OS through interop shims (Interop.Sys is libSystem.Native). They are linked into
the host binary as static archives, so Mono cannot dlopen them by name. This emits a name-to-address
table that the engine serves from a Mono dl fallback handler; referencing each symbol from the table
is also what makes the linker pull the owning object file out of the archive.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

# nm prints one symbol per line as "<address> <type> <name>"; T/t are text, W/w weak text. Data
# symbols are never P/Invoke targets, so they are dropped
SYMBOL_LINE_RE = re.compile(r'^\s*(?:[0-9a-fA-F]+)?\s*([TtWw])\s+(\S+)$')

# A shim entry point is a plain C identifier. Anything else is a toolchain artefact (local labels,
# mangled helpers) that must not reach the generated declarations
SYMBOL_NAME_RE = re.compile(r'^[A-Za-z_][A-Za-z0-9_]*$')


def collect_archive_symbols(nm_tool: str, archive_path: Path, prefix: str) -> list[str]:
    try:
        output = subprocess.check_output([nm_tool, '--defined-only', '-g', str(archive_path)], text=True, encoding='utf-8', errors='replace')
    except (OSError, subprocess.CalledProcessError) as ex:
        raise SystemExit(f'Failed to read symbols from {archive_path}: {ex}') from ex

    symbols: set[str] = set()

    for line in output.splitlines():
        match = SYMBOL_LINE_RE.match(line)

        if match is None:
            continue

        name = match.group(2)

        # Mach-O nm reports C symbols with a leading underscore that is not part of the entry point name
        if name.startswith('_') and not name.startswith(prefix):
            name = name[1:]

        if name.startswith(prefix) and SYMBOL_NAME_RE.match(name) is not None:
            symbols.add(name)

    if not symbols:
        raise SystemExit(f'No {prefix}* entry points found in {archive_path}')

    return sorted(symbols)


def emit_table(output_path: Path, libraries: dict[str, list[str]]) -> None:
    lines: list[str] = []
    lines.append('// Generated by Engine/BuildTools/generate_pinvoke_table.py, do not edit')
    lines.append('')
    lines.append('#include "ManagedPInvokeTable.h"')
    lines.append('')
    lines.append('// Declared as niladic and outside the engine namespace: only the address is ever taken, never a')
    lines.append('// call, so the real signature is irrelevant and reproducing every shim prototype would not pay')
    lines.append('extern "C" {')

    for symbols in libraries.values():
        for symbol in symbols:
            lines.append(f'void {symbol}();')

    lines.append('}')
    lines.append('')
    lines.append('FO_BEGIN_NAMESPACE')
    lines.append('')
    entries = [f'    {{"{library_name}", "{symbol}", reinterpret_cast<const void*>(&{symbol})}},'
               for library_name, symbols in libraries.items() for symbol in symbols]

    # The header declares the array with an unknown bound, so an empty table still needs one element to
    # be a well-formed definition; the count is what callers read
    if entries:
        lines.append('const ManagedPInvokeEntry ManagedPInvokeEntries[] = {')
        lines.extend(entries)
        lines.append('};')
        lines.append('')
        lines.append('const size_t ManagedPInvokeEntryCount = sizeof(ManagedPInvokeEntries) / sizeof(ManagedPInvokeEntries[0]);')
    else:
        lines.append('const ManagedPInvokeEntry ManagedPInvokeEntries[1] = {};')
        lines.append('')
        lines.append('const size_t ManagedPInvokeEntryCount = 0;')
    lines.append('')
    lines.append('FO_END_NAMESPACE')
    lines.append('')

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text('\n'.join(lines), encoding='utf-8')


def parse_library_argument(value: str) -> tuple[str, str, Path]:
    parts = value.split('=')

    if len(parts) != 3:
        raise argparse.ArgumentTypeError(f'Expected <library>=<prefix>=<archive>, got: {value}')

    library_name, prefix, archive = parts
    return library_name, prefix, Path(archive)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--nm', required=True, help='nm tool of the target toolchain')
    parser.add_argument('--output', required=True, type=Path, help='generated source file')
    # A target may link no shim at all: Windows resolves CoreLib's P/Invokes through Win32 itself
    parser.add_argument('--library', action='append', default=[], type=parse_library_argument, help='<library>=<prefix>=<archive>, repeatable')
    parser.add_argument('--exclude', action='append', default=[], help='entry point the target cannot support, repeatable')
    args = parser.parse_args()

    libraries: dict[str, list[str]] = {}
    excluded = set(args.exclude)
    seen: set[str] = set()

    for library_name, prefix, archive_path in args.library:
        if not archive_path.is_file():
            raise SystemExit(f'Interop shim archive not found: {archive_path}')

        symbols = collect_archive_symbols(args.nm, archive_path, prefix)
        seen.update(symbols)
        kept = [name for name in symbols if name not in excluded]
        dropped = len(symbols) - len(kept)
        libraries[library_name] = kept

        if dropped != 0:
            print(f'{library_name}: {len(kept)} entry points ({dropped} excluded)', file=sys.stderr)
        else:
            print(f'{library_name}: {len(kept)} entry points', file=sys.stderr)

    # An exclusion that matches nothing is a typo or a renamed entry point, and it fails silently: the
    # object it was meant to drop stays live and only surfaces as an undefined symbol at link time
    unmatched = sorted(excluded - seen)

    if unmatched:
        raise SystemExit(f'Excluded entry points not found in any archive: {", ".join(unmatched)}')

    emit_table(args.output, libraries)


if __name__ == '__main__':
    main()
