# CMake initial cache

if(NOT DEFINED ENV{FO_ENGINE_ROOT})
	message(FATAL_ERROR "Define FO_ENGINE_ROOT")
endif()

file(READ "${CMAKE_CURRENT_LIST_DIR}/../ThirdParty/iOS-sdk" FO_IOS_SDK_VERSION)
string(STRIP "${FO_IOS_SDK_VERSION}" FO_IOS_SDK_VERSION)

set(CMAKE_SYSTEM_NAME "iOS" CACHE STRING "Forced by FOnline" FORCE)
set(CMAKE_SYSTEM_VERSION "-" CACHE STRING "Forced by FOnline" FORCE)
set(CMAKE_TOOLCHAIN_FILE "$ENV{FO_ENGINE_ROOT}/BuildTools/ios.toolchain.cmake" CACHE PATH "Forced by FOnline" FORCE)
set(PLATFORM "SIMULATOR64" CACHE STRING "Forced by FOnline" FORCE)
set(DEPLOYMENT_TARGET ${FO_IOS_SDK_VERSION} CACHE STRING "Forced by FOnline" FORCE)
set(ENABLE_BITCODE OFF CACHE BOOL "Forced by FOnline" FORCE)
set(ENABLE_ARC OFF CACHE BOOL "Forced by FOnline" FORCE)
set(ENABLE_VISIBILITY OFF CACHE BOOL "Forced by FOnline" FORCE)
set(ENABLE_STRICT_TRY_COMPILE OFF CACHE BOOL "Forced by FOnline" FORCE)

# set( PLATFORM "OS64" CACHE STRING "Forced by FOnline" FORCE )
# set( CMAKE_XCODE_ATTRIBUTE_PRODUCT_BUNDLE_IDENTIFIER "com.fonline.default" CACHE STRING "Forced by FOnline" FORCE )
# set( CMAKE_XCODE_ATTRIBUTE_DEVELOPMENT_TEAM "..." CACHE STRING "Forced by FOnline" FORCE )
