@echo off
setlocal

call "%~dp0\setup-env.cmd"

if not exist "%FO_WORKSPACE%" mkdir "%FO_WORKSPACE%"
pushd "%FO_WORKSPACE%""

set VALIDATION_PROJECT_ROOT=%FO_WORKSPACE%\validation-project
if not exist "%VALIDATION_PROJECT_ROOT%" mkdir "%VALIDATION_PROJECT_ROOT%"
xcopy /s /e /y /D "%FO_ENGINE_ROOT%\BuildTools\validation-project\*" "%VALIDATION_PROJECT_ROOT%\" >nul
if not exist "%VALIDATION_PROJECT_ROOT%\Engine" mklink /d "%VALIDATION_PROJECT_ROOT%\Engine" "%FO_ENGINE_ROOT%"

if [%1] == [win32-client] (
    set BUILD_TARGET=-DFO_BUILD_CLIENT=1 -DFO_BUILD_SERVER=0 -DFO_BUILD_EDITOR=0 -DFO_BUILD_MAPPER=0 -DFO_BUILD_ASCOMPILER=0 -DFO_BUILD_BAKER=0 -DFO_UNIT_TESTS=0 -DFO_CODE_COVERAGE=0
    set BUILD_ARCH=Win32
) else if [%1] == [win64-client] (
    set BUILD_TARGET=-DFO_BUILD_CLIENT=1 -DFO_BUILD_SERVER=0 -DFO_BUILD_EDITOR=0 -DFO_BUILD_MAPPER=0 -DFO_BUILD_ASCOMPILER=0 -DFO_BUILD_BAKER=0 -DFO_UNIT_TESTS=0 -DFO_CODE_COVERAGE=0
    set BUILD_ARCH=x64
) else if [%1] == [win64-clang-client] (
    set BUILD_TARGET=-DFO_BUILD_CLIENT=1 -DFO_BUILD_SERVER=0 -DFO_BUILD_EDITOR=0 -DFO_BUILD_MAPPER=0 -DFO_BUILD_ASCOMPILER=0 -DFO_BUILD_BAKER=0 -DFO_UNIT_TESTS=0 -DFO_CODE_COVERAGE=0
    set BUILD_ARCH=x64
    set BUILD_TOOLSET=ClangCL
) else if [%1] == [win64-server] (
    set BUILD_TARGET=-DFO_BUILD_CLIENT=0 -DFO_BUILD_SERVER=1 -DFO_BUILD_EDITOR=0 -DFO_BUILD_MAPPER=0 -DFO_BUILD_ASCOMPILER=0 -DFO_BUILD_BAKER=0 -DFO_UNIT_TESTS=0 -DFO_CODE_COVERAGE=0
    set BUILD_ARCH=x64
) else if [%1] == [win64-clang-server] (
    set BUILD_TARGET=-DFO_BUILD_CLIENT=0 -DFO_BUILD_SERVER=1 -DFO_BUILD_EDITOR=0 -DFO_BUILD_MAPPER=0 -DFO_BUILD_ASCOMPILER=0 -DFO_BUILD_BAKER=0 -DFO_UNIT_TESTS=0 -DFO_CODE_COVERAGE=0
    set BUILD_ARCH=x64
    set BUILD_TOOLSET=ClangCL
) else if [%1] == [win64-editor] (
    set BUILD_TARGET=-DFO_BUILD_CLIENT=0 -DFO_BUILD_SERVER=0 -DFO_BUILD_EDITOR=1 -DFO_BUILD_MAPPER=0 -DFO_BUILD_ASCOMPILER=0 -DFO_BUILD_BAKER=0 -DFO_UNIT_TESTS=0 -DFO_CODE_COVERAGE=0
    set BUILD_ARCH=x64
) else if [%1] == [win64-mapper] (
    set BUILD_TARGET=-DFO_BUILD_CLIENT=0 -DFO_BUILD_SERVER=0 -DFO_BUILD_EDITOR=0 -DFO_BUILD_MAPPER=1 -DFO_BUILD_ASCOMPILER=0 -DFO_BUILD_BAKER=0 -DFO_UNIT_TESTS=0 -DFO_CODE_COVERAGE=0
    set BUILD_ARCH=x64
) else if [%1] == [win64-ascompiler] (
    set BUILD_TARGET=-DFO_BUILD_CLIENT=0 -DFO_BUILD_SERVER=0 -DFO_BUILD_EDITOR=0 -DFO_BUILD_MAPPER=0 -DFO_BUILD_ASCOMPILER=1 -DFO_BUILD_BAKER=0 -DFO_UNIT_TESTS=0 -DFO_CODE_COVERAGE=0
    set BUILD_ARCH=x64
) else if [%1] == [win64-clang-ascompiler] (
    set BUILD_TARGET=-DFO_BUILD_CLIENT=0 -DFO_BUILD_SERVER=0 -DFO_BUILD_EDITOR=0 -DFO_BUILD_MAPPER=0 -DFO_BUILD_ASCOMPILER=1 -DFO_BUILD_BAKER=0 -DFO_UNIT_TESTS=0 -DFO_CODE_COVERAGE=0
    set BUILD_ARCH=x64
    set BUILD_TOOLSET=ClangCL
) else if [%1] == [win64-baker] (
    set BUILD_TARGET=-DFO_BUILD_CLIENT=0 -DFO_BUILD_SERVER=0 -DFO_BUILD_EDITOR=0 -DFO_BUILD_MAPPER=0 -DFO_BUILD_ASCOMPILER=0 -DFO_BUILD_BAKER=1 -DFO_UNIT_TESTS=0 -DFO_CODE_COVERAGE=0
    set BUILD_ARCH=x64
) else if [%1] == [win64-clang-baker] (
    set BUILD_TARGET=-DFO_BUILD_CLIENT=0 -DFO_BUILD_SERVER=0 -DFO_BUILD_EDITOR=0 -DFO_BUILD_MAPPER=0 -DFO_BUILD_ASCOMPILER=0 -DFO_BUILD_BAKER=1 -DFO_UNIT_TESTS=0 -DFO_CODE_COVERAGE=0
    set BUILD_ARCH=x64
    set BUILD_TOOLSET=ClangCL
) else if [%1] == [unit-tests] (
    set BUILD_TARGET=-DFO_BUILD_CLIENT=0 -DFO_BUILD_SERVER=0 -DFO_BUILD_EDITOR=0 -DFO_BUILD_MAPPER=0 -DFO_BUILD_ASCOMPILER=0 -DFO_BUILD_BAKER=0 -DFO_UNIT_TESTS=1 -DFO_CODE_COVERAGE=0
    set BUILD_ARCH=x64
) else (
    echo Invalid build argument
    exit /b 1
)

set BUILD_DIR=validate-%1
if not exist %BUILD_DIR% mkdir %BUILD_DIR%
cd %BUILD_DIR%

if not [%BUILD_TOOLSET%] == [] (
    cmake -A %BUILD_ARCH% -T %BUILD_TOOLSET% %BUILD_TARGET% "%VALIDATION_PROJECT_ROOT%"
    if errorlevel 1 exit /b 1
) else (
    cmake -A %BUILD_ARCH% %BUILD_TARGET% "%VALIDATION_PROJECT_ROOT%"
    if errorlevel 1 exit /b 1
)

cmake --build . --config Debug --parallel
if errorlevel 1 exit /b 1

popd
exit /b
