include_guard()

function(TryGetEnvOptionOverride var optionType hasOverrideOut valueOut)
	set(hasOverride OFF)
	set(overrideValue "")

	if("${var}" MATCHES "^FO_" AND DEFINED ENV{${var}})
		set(hasOverride ON)
		set(overrideValue "$ENV{${var}}")

		if("${optionType}" STREQUAL "BOOL")
			string(TOUPPER "${overrideValue}" overrideValueNormalized)

			if(
				overrideValueNormalized STREQUAL "1" OR
				overrideValueNormalized STREQUAL "ON" OR
				overrideValueNormalized STREQUAL "TRUE" OR
				overrideValueNormalized STREQUAL "YES")
				set(overrideValue ON)
			elseif(
				overrideValueNormalized STREQUAL "0" OR
				overrideValueNormalized STREQUAL "OFF" OR
				overrideValueNormalized STREQUAL "FALSE" OR
				overrideValueNormalized STREQUAL "NO")
				set(overrideValue OFF)
			else()
				AbortMessage("Invalid boolean environment override ${var}='$ENV{${var}}'. Use 1/0, ON/OFF, TRUE/FALSE, or YES/NO")
			endif()
		endif()
	endif()

	set(${hasOverrideOut} ${hasOverride} PARENT_SCOPE)
	set(${valueOut} "${overrideValue}" PARENT_SCOPE)
endfunction()

macro(DeclareBoolOption var desc value)
	TryGetEnvOptionOverride("${var}" "BOOL" hasEnvOverride envOverrideValue)

	if(hasEnvOverride)
		set(${var} ${envOverrideValue})
	elseif(NOT DEFINED ${var})
		set(${var} ${value})
	endif()

	option(${var} "${desc}" ${value})

	if(hasEnvOverride)
		set(${var} ${envOverrideValue} CACHE BOOL "${desc}" FORCE)
		StatusMessage("${var} = ${${var}} (env)")
	else()
		StatusMessage("${var} = ${${var}}")
	endif()
endmacro()

macro(DeclareValueOption var desc value)
	TryGetEnvOptionOverride("${var}" "STRING" hasEnvOverride envOverrideValue)
	GetCacheProperty(cacheType ${var} TYPE)

	if(cacheType STREQUAL "BOOL" AND ("${${var}}" STREQUAL "ON" OR "${${var}}" STREQUAL "OFF"))
		set(${var} "${value}")
	endif()

	if(hasEnvOverride)
		set(${var} "${envOverrideValue}")
	elseif(NOT DEFINED ${var} OR "${${var}}" STREQUAL "")
		set(${var} "${value}")
	endif()

	set(${var} "${${var}}" CACHE STRING "${desc}" FORCE)

	if(hasEnvOverride)
		StatusMessage("${var} = ${${var}} (env)")
	else()
		StatusMessage("${var} = ${${var}}")
	endif()
endmacro()

macro(DeclareBoolOptions)
	set(optionArgs "${ARGN}")
	ListLength(optionArgs optionArgsCount)
	MathExpr(optionArgsRemainder "${optionArgsCount} % 3")

	if(NOT optionArgsRemainder EQUAL 0)
		AbortMessage("DeclareBoolOptions expects groups of 3 arguments")
	endif()

	while(optionArgs)
		ListPopFront(optionArgs optionName optionDesc optionValue)
		DeclareBoolOption(${optionName} "${optionDesc}" ${optionValue})
	endwhile()
endmacro()

macro(DeclareRequiredValueOptions)
	set(optionArgs "${ARGN}")
	ListLength(optionArgs optionArgsCount)
	MathExpr(optionArgsRemainder "${optionArgsCount} % 2")

	if(NOT optionArgsRemainder EQUAL 0)
		AbortMessage("DeclareRequiredValueOptions expects pairs of arguments")
	endif()

	while(optionArgs)
		ListPopFront(optionArgs optionName optionDesc)
		DeclareValueOption(${optionName} "${optionDesc}" "")
	endwhile()
endmacro()

macro(DeclareValueOptions)
	set(optionArgs "${ARGN}")
	ListLength(optionArgs optionArgsCount)
	MathExpr(optionArgsRemainder "${optionArgsCount} % 3")

	if(NOT optionArgsRemainder EQUAL 0)
		AbortMessage("DeclareValueOptions expects groups of 3 arguments")
	endif()

	while(optionArgs)
		ListPopFront(optionArgs optionName optionDesc optionValue)
		DeclareValueOption(${optionName} "${optionDesc}" "${optionValue}")
	endwhile()
endmacro()

function(LoadProjectInterface interfacePath outputVar)
	if(NOT EXISTS "${interfacePath}")
		AbortMessage("FOnline project interface manifest not found: ${interfacePath}")
	endif()

	file(READ "${interfacePath}" interfaceJson)
	string(JSON interfaceSchema GET "${interfaceJson}" schema_version)

	if(NOT interfaceSchema EQUAL 1)
		AbortMessage("Unsupported FOnline project interface schema: ${interfaceSchema}")
	endif()

	set(${outputVar} "${interfaceJson}" PARENT_SCOPE)
endfunction()

function(LoadNativeExtensionInterface interfacePath outputJsonVar outputRolesVar)
	if(NOT EXISTS "${interfacePath}")
		AbortMessage("FOnline native extension interface manifest not found: ${interfacePath}")
	endif()

	file(READ "${interfacePath}" interfaceJson)
	string(JSON interfaceSchema GET "${interfaceJson}" schema_version)
	string(JSON interfaceSurface GET "${interfaceJson}" scope surface)
	if(NOT interfaceSchema EQUAL 1)
		AbortMessage("Unsupported FOnline native extension interface schema: ${interfaceSchema}")
	endif()
	if(NOT interfaceSurface STREQUAL "native-extension-interface")
		AbortMessage("Invalid FOnline native extension interface surface: ${interfaceSurface}")
	endif()

	string(JSON roleCount LENGTH "${interfaceJson}" roles)
	if(roleCount LESS 1)
		AbortMessage("FOnline native extension interface must declare at least one role")
	endif()

	set(roleNames "")
	math(EXPR lastRoleIndex "${roleCount} - 1")
	foreach(roleIndex RANGE 0 ${lastRoleIndex})
		string(JSON roleName GET "${interfaceJson}" roles ${roleIndex} name)
		if(NOT roleName MATCHES "^[A-Z][A-Z0-9_]*$")
			AbortMessage("Invalid FOnline native extension role: ${roleName}")
		endif()
		if("${roleName}" IN_LIST roleNames)
			AbortMessage("Duplicate FOnline native extension role: ${roleName}")
		endif()
		list(APPEND roleNames "${roleName}")
	endforeach()

	set(${outputJsonVar} "${interfaceJson}" PARENT_SCOPE)
	set(${outputRolesVar} "${roleNames}" PARENT_SCOPE)
endfunction()

macro(ValidateProjectInterfaceNativeExtensionRoles projectInterfaceJsonVar)
	set(_foProjectInterfaceJson "${${projectInterfaceJsonVar}}")
	string(JSON _foHelperCount LENGTH "${_foProjectInterfaceJson}" helpers)
	set(_foProjectNativeExtensionRoles "")
	if(_foHelperCount GREATER 0)
		math(EXPR _foLastHelperIndex "${_foHelperCount} - 1")
		foreach(_foHelperIndex RANGE 0 ${_foLastHelperIndex})
			string(JSON _foHelperName GET "${_foProjectInterfaceJson}" helpers ${_foHelperIndex} name)
			if(_foHelperName STREQUAL "AddEngineSources")
				string(JSON _foRoleCount LENGTH "${_foProjectInterfaceJson}" helpers ${_foHelperIndex} allowed_roles)
				if(_foRoleCount GREATER 0)
					math(EXPR _foLastRoleIndex "${_foRoleCount} - 1")
					foreach(_foRoleIndex RANGE 0 ${_foLastRoleIndex})
						string(JSON _foRole GET "${_foProjectInterfaceJson}" helpers ${_foHelperIndex} allowed_roles ${_foRoleIndex})
						list(APPEND _foProjectNativeExtensionRoles "${_foRole}")
					endforeach()
				endif()
			endif()
		endforeach()
	endif()

	if(NOT "${_foProjectNativeExtensionRoles}" STREQUAL "${FO_NATIVE_EXTENSION_ROLES}")
		AbortMessage("Project and native extension interface roles differ: project='${_foProjectNativeExtensionRoles}', native='${FO_NATIVE_EXTENSION_ROLES}'")
	endif()
endmacro()

macro(LoadProjectInterfaceStages interfaceJsonVar)
	set(_foInterfaceJson "${${interfaceJsonVar}}")
	string(JSON _foStageCount LENGTH "${_foInterfaceJson}" stages)

	if(_foStageCount LESS 1)
		AbortMessage("FOnline project interface must declare at least one stage")
	endif()

	set(FO_KNOWN_STAGES "")
	set(_foKnownStageEntrypoints "")
	math(EXPR _foLastStageIndex "${_foStageCount} - 1")

	foreach(_foStageIndex RANGE 0 ${_foLastStageIndex})
		string(JSON _foStageOrder GET "${_foInterfaceJson}" stages ${_foStageIndex} order)
		string(JSON _foStageName GET "${_foInterfaceJson}" stages ${_foStageIndex} name)
		string(JSON _foStageEntrypoint GET "${_foInterfaceJson}" stages ${_foStageIndex} entrypoint)
		math(EXPR _foExpectedStageOrder "${_foStageIndex} + 1")

		if(NOT _foStageOrder EQUAL _foExpectedStageOrder)
			AbortMessage("FOnline project interface stage order must be contiguous at ${_foStageName}")
		endif()
		if("${_foStageName}" IN_LIST FO_KNOWN_STAGES)
			AbortMessage("Duplicate FOnline project interface stage: ${_foStageName}")
		endif()
		if("${_foStageEntrypoint}" IN_LIST _foKnownStageEntrypoints)
			AbortMessage("Duplicate FOnline project interface stage entrypoint: ${_foStageEntrypoint}")
		endif()

		list(APPEND FO_KNOWN_STAGES "${_foStageName}")
		list(APPEND _foKnownStageEntrypoints "${_foStageEntrypoint}")
		set(FO_STAGE_ENTRYPOINT_${_foStageName} "${_foStageEntrypoint}")
		set(FO_STAGE_HOOKS_${_foStageName} "")
		string(JSON _foStageHookCount LENGTH "${_foInterfaceJson}" stages ${_foStageIndex} hooks)

		if(_foStageHookCount GREATER 0)
			math(EXPR _foLastStageHookIndex "${_foStageHookCount} - 1")
			foreach(_foStageHookIndex RANGE 0 ${_foLastStageHookIndex})
				string(JSON _foStageHook GET "${_foInterfaceJson}" stages ${_foStageIndex} hooks ${_foStageHookIndex})
				if(NOT _foStageHook STREQUAL "Pre" AND NOT _foStageHook STREQUAL "Post")
					AbortMessage("Unsupported hook point ${_foStageHook} for stage ${_foStageName}")
				endif()
				list(APPEND FO_STAGE_HOOKS_${_foStageName} "${_foStageHook}")
			endforeach()
		endif()
	endforeach()
endmacro()

macro(DeclareProjectInterfaceOptions interfaceJsonVar)
	set(_foInterfaceJson "${${interfaceJsonVar}}")
	string(JSON _foOptionCount LENGTH "${_foInterfaceJson}" options)

	if(_foOptionCount LESS 1)
		AbortMessage("FOnline project interface must declare at least one option")
	endif()

	set(_foKnownProjectOptions "")
	math(EXPR _foLastOptionIndex "${_foOptionCount} - 1")
	foreach(_foOptionIndex RANGE 0 ${_foLastOptionIndex})
		string(JSON _foOptionName GET "${_foInterfaceJson}" options ${_foOptionIndex} name)
		string(JSON _foOptionCacheType GET "${_foInterfaceJson}" options ${_foOptionIndex} cache_type)
		string(JSON _foOptionRequired GET "${_foInterfaceJson}" options ${_foOptionIndex} required)
		string(JSON _foOptionDescription GET "${_foInterfaceJson}" options ${_foOptionIndex} description)
		string(JSON _foOptionDefaultType TYPE "${_foInterfaceJson}" options ${_foOptionIndex} default)

		if(NOT _foOptionName MATCHES "^FO_[A-Z0-9_]+$")
			AbortMessage("Invalid FOnline project option name: ${_foOptionName}")
		endif()
		if("${_foOptionName}" IN_LIST _foKnownProjectOptions)
			AbortMessage("Duplicate FOnline project option: ${_foOptionName}")
		endif()
		list(APPEND _foKnownProjectOptions "${_foOptionName}")

		if(_foOptionRequired)
			if(NOT _foOptionCacheType STREQUAL "STRING" OR NOT _foOptionDefaultType STREQUAL "NULL")
				AbortMessage("Required FOnline project option ${_foOptionName} must be STRING with a null default")
			endif()
			DeclareValueOption(${_foOptionName} "${_foOptionDescription}" "")
		else()
			if(_foOptionDefaultType STREQUAL "NULL")
				AbortMessage("Optional FOnline project option ${_foOptionName} must declare a default")
			endif()
			string(JSON _foOptionDefault GET "${_foInterfaceJson}" options ${_foOptionIndex} default)
			string(CONFIGURE "${_foOptionDefault}" _foOptionDefault)

			if(_foOptionCacheType STREQUAL "BOOL")
				DeclareBoolOption(${_foOptionName} "${_foOptionDescription}" ${_foOptionDefault})
			elseif(_foOptionCacheType STREQUAL "STRING")
				DeclareValueOption(${_foOptionName} "${_foOptionDescription}" "${_foOptionDefault}")
			else()
				AbortMessage("Unsupported cache type ${_foOptionCacheType} for ${_foOptionName}")
			endif()
		endif()
	endforeach()
endmacro()

macro(ValidateProjectInterfaceHelpers interfaceJsonVar)
	set(_foInterfaceJson "${${interfaceJsonVar}}")
	string(JSON _foHelperCount LENGTH "${_foInterfaceJson}" helpers)
	if(_foHelperCount GREATER 0)
		math(EXPR _foLastHelperIndex "${_foHelperCount} - 1")
		foreach(_foHelperIndex RANGE 0 ${_foLastHelperIndex})
			string(JSON _foHelperName GET "${_foInterfaceJson}" helpers ${_foHelperIndex} name)
			if(NOT COMMAND ${_foHelperName})
				AbortMessage("FOnline project interface helper is not defined: ${_foHelperName}")
			endif()
		endforeach()
	endif()
endmacro()
