include_guard()

# Temporary variables
SetDefaultVariables(""
	FO_ENGINE_ROOT
	FO_BUILD_HASH
	FO_GIT_ROOT
	FO_GIT_HASH_RESULT
	FO_GIT_HASH
	FO_GEN_DEPENDENCIES
	FO_CLIENT_OUTPUT
	FO_SERVER_OUTPUT
	FO_EDITOR_OUTPUT
	FO_MAPPER_OUTPUT
	FO_ASCOMPILER_OUTPUT
	FO_BAKER_OUTPUT
	FO_TESTS_OUTPUT
	FO_PROCESSOR_ARCHITECTURE
	FO_BUILD_PLATFORM
	FO_ESSENTIALS_SYSTEM_LIBS
	FO_ESSENTIALS_LIBS
	FO_COMMON_SYSTEM_LIBS
	FO_COMMON_LIBS
	FO_SERVER_SYSTEM_LIBS
	FO_SERVER_LIBS
	FO_CLIENT_SYSTEM_LIBS
	FO_CLIENT_LIBS
	FO_RENDER_SYSTEM_LIBS
	FO_RENDER_LIBS
	FO_BAKER_SYSTEM_LIBS
	FO_BAKER_LIBS
	FO_TESTING_LIBS
	FO_DUMMY_TARGETS
	FO_RPMALLOC_DIR
	FO_SDL_DIR
	FO_TRACY_DIR
	FO_ZLIB_DIR
	FO_PNG_DIR
	FO_OGG_DIR
	FO_VORBIS_DIR
	FO_THEORA_DIR
	FO_ACM_DIR
	FO_SHA_DIR
	FO_GLEW_DIR
	FO_UFBX_DIR
	FO_JSON_DIR
	FO_FMT_DIR
	FO_ASIO_DIR
	FO_WEBSOCKETS_DIR
	FO_MONGODB_DIR
	FO_UNQLITE_DIR
	FO_VARIANT_DIR
	FO_LIBRESSL_DIR
	FO_DEAR_IMGUI_DIR
	FO_CATCH2_DIR
	FO_BACKWARDCPP_DIR
	FO_SPARK_DIR
	FO_GLSLANG_DIR
	FO_SPIRV_CROSS_DIR
	FO_ANGELSCRIPT_SCRIPTING_DIR
	FO_ANGELSCRIPT_SDK_DIR
	FO_ANGELSCRIPT_PREPROCESSOR_DIR
	FO_ACM_SOURCE
	FO_SHA_SOURCE
	FO_ZLIB_CONTRIB_SOURCE
	FO_CATCH2_SOURCE
	FO_DOTNET_DIR
	FO_MONO_OS
	FO_MONO_ARCH
	FO_MONO_CONFIGURATION
	FO_MONO_TRIPLET
	FO_MONO_SETUP_SCRIPT
	FO_RPMALLOC_SOURCE
	FO_OGG_SOURCE
	FO_VORBIS_SOURCE
	FO_THEORA_SOURCE
	FO_GLEW_SOURCE
	FO_UFBX_SOURCE
	FO_IMGUI_SOURCE
	FO_ESSENTIALS_SOURCE
	FO_COMMON_SOURCE
	FO_SERVER_BASE_SOURCE
	FO_CLIENT_BASE_SOURCE
	FO_SERVER_SOURCE
	FO_CLIENT_SOURCE
	FO_EDITOR_SOURCE
	FO_MAPPER_SOURCE
	FO_BAKER_SOURCE
	FO_SOURCE_META_FILES
	FO_TESTS_SOURCE
	FO_ADDED_COMMON_HEADERS
	FO_CORE_LIBS_GROUP
	FO_COMMANDS_GROUP
	FO_APPLICATIONS_GROUP
	FO_CACHE_VARIABLES
	FO_CONTRIBUTION_DIR
	FO_SPRITE_ATLAS
	FO_CODEGEN_COMMAND
	FO_CODEGEN_COMMAND_ARGS
	FO_CODEGEN_META_SOURCE
	FO_CODEGEN_OUTPUT
	FO_PACKAGES
	FO_RC_FILE
	FO_CONFIG_VAR_LIST)

set(FO_CONFIGURATION_TYPES "Debug;Release;RelWithDebInfo;MinSizeRel")
SetDefaultVariables(OFF
	FO_MULTICONFIG
	FO_BUILD_LIBRARY
	FO_BUILD_COMMON_LIB
	FO_BUILD_CLIENT_LIB
	FO_BUILD_SERVER_LIB
	FO_BUILD_MAPPER_LIB
	FO_BUILD_BAKER_LIB
	FO_BUILD_EDITOR_LIB
	FO_USE_GLEW)

SetDefaultVariables(ON FO_HEADLESS_ONLY)

SetDefaultVariables(0
	FO_WINDOWS
	FO_LINUX
	FO_MAC
	FO_ANDROID
	FO_IOS
	FO_WEB
	FO_HAVE_OPENGL
	FO_OPENGL_ES
	FO_HAVE_DIRECT_3D
	FO_HAVE_METAL
	FO_HAVE_VULKAN)

# Configuration duplication
SetValue(configVarsFile "${CMAKE_CURRENT_BINARY_DIR}/cmake-vars.txt")
ExecuteProcess(
	COMMAND ${CMAKE_COMMAND} --help-variable-list
	OUTPUT_FILE "${configVarsFile}")
FileReadStrings("${configVarsFile}" configVarFullList)

foreach(configVar ${configVarFullList})
	if("${configVar}" MATCHES "<CONFIG>")
		if("${configVar}" MATCHES "<LANG>")
			foreach(lang
				C CXX CSharp CUDA OBJC OBJCXX Fortran HIP ISPC Swift ASM ASM_NASM ASM_MARMASM ASM_MASM ASM-ATT)
				StringReplace("<LANG>" "${lang}" langConfigVar "${configVar}")
				AppendList(FO_CONFIG_VAR_LIST "${langConfigVar}")
			endforeach()
		else()
			AppendList(FO_CONFIG_VAR_LIST "${configVar}")
		endif()
	endif()
endforeach()

function(CopyConfigurationType configFrom configTo)
	StringToUpper("${configFrom}" configFrom)
	StringToUpper("${configTo}" configTo)

	foreach(configVar ${FO_CONFIG_VAR_LIST})
		StringReplace("<CONFIG>" "${configFrom}" configVarFrom "${configVar}")
		StringReplace("<CONFIG>" "${configTo}" configVarTo "${configVar}")

		if(NOT "${${configVarFrom}}" STREQUAL "")
			set("${configVarTo}" "${${configVarFrom}}" PARENT_SCOPE)
		endif()
	endforeach()
endfunction()

# Evaluate engine root
GetFilenameComponent(FO_ENGINE_ROOT ${FO_BUILDTOOLS_DIR}/.. ABSOLUTE)
cmake_path(RELATIVE_PATH FO_ENGINE_ROOT BASE_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
