#ifndef ERROR_INCLUDED
#define ERROR_INCLUDED

enum
{
   RES_OK,
   ERR_CANNOT_OPEN_FILE,
   ERR_FILE_TRUNCATED,
   ERR_FILE_NOT_SUPPORTED,
   ERR_ALLOC_MEMORY,
   ERR_CANNOT_OPEN_DAT_FILE,
   ERR_CANNOT_CREATE_OUT_FILE,
   ERR_CANNOT_WRITE_TO_FILE,
   ERR_UNKNOWN
};

#endif
