// This file uses nullable-reference annotations and the baker copies it verbatim under an
// `// <auto-generated />` banner. Generated code ignores nullable annotations unless the file carries an
// explicit `#nullable` directive (CS8669), so opt into the enabled context like the other hand-written
// CoreScripts (Verify.cs) and the generated entity/type files do.
#nullable enable

namespace FOnline
{
    // `Game` is a partial static class whose other parts are generated per target; this part adds the
    // game-state helpers below.
    public static partial class Game
    {
        // Managed equivalent of the per-enum AngelScript `Game.EnumToString(<Enum> value, bool fullSpecification)`
        // (AngelScriptGlobals.cpp Game_EnumToString -> EngineMetadata::ResolveEnumValueName): returns the enum
        // member's name, or `EnumType::Member` when fullSpecification is set. The generated managed enums carry the
        // same member names as the engine metadata, so Enum.GetName matches AngelScript's resolution; an undefined
        // value (including a [Flags] combination) throws, mirroring the engine's "Invalid enum index". AngelScript
        // registers one overload per enum type; this single generic covers them all.
        public static string EnumToString<T>(T value, bool fullSpecification = false)
            where T : struct, System.Enum
        {
            string? name = System.Enum.GetName(value);
            Verify(name != null, "Invalid enum index", typeof(T).Name, value);
            return fullSpecification ? typeof(T).Name + "::" + name! : name!;
        }
    }
}
