// This file uses nullable-reference annotations (T?), and the baker copies it verbatim under an
// `// <auto-generated />` banner. Generated code ignores nullable annotations unless the file carries an
// explicit `#nullable` directive (CS8669), so opt this file into the enabled context like the generated
// entity/type files do.
#nullable enable

namespace FOnline
{
    // Managed equivalent of the always-on AngelScript `verify(cond, message[, ...args])` macro
    // (Engine/Source/Scripting/AngelScript/CoreScripts/Core.fos): an invariant check that throws when the
    // condition is false, never stripped in any build. The AngelScript macro expands to `throw(message, args...)`
    // (AngelScriptGlobals.cpp Global_ThrowException -> ScriptException), whose message is the message followed by
    // one "\n- <arg>" line per context value (ExceptionHandling.h). A thrown managed exception is caught by
    // Native.InvokeEvent, logged via Native.Log, and converts the event to StopChain -- mirroring AngelScript's
    // "violated verify => logged, chain stopped" behavior, so no new native binding is needed.
    //
    // The port tool (Tools/ManagedPort) rewrites `verify(...)` -> `Game.Verify(...)`; ported modules import
    // `FOnline`, so `Game` resolves here without an extra `using`. `Game` is a partial static class (its other
    // parts are generated per target), so this file only contributes the invariant helpers.
    public static partial class Game
    {
        // `[DoesNotReturnIf(false)]` on the condition is what makes an invariant check mean something to the
        // compiler, exactly as it does for System.Diagnostics.Debug.Assert. It states that the method does not
        // return when `condition` is false, so past the call the flow analysis may assume it was true. For the
        // dominant form `Verify(x != null, ...)` that narrows `x` to non-null for the rest of the method, and
        // the `x!` suppressions that would otherwise be needed afterwards become unnecessary.
        //
        // This only reaches conditions the null-state analysis can follow -- `Verify(x != null, ...)` narrows,
        // `Verify(IsValid(x), ...)` cannot, since nothing ties the helper's result to x's null state. Annotate
        // such a helper with `[MemberNotNullWhen]`/`[NotNullWhen]` rather than reaching for `!` at the call.

        // verify(cond, message) -- the common form. Throws when the invariant is broken.
        public static void Verify([System.Diagnostics.CodeAnalysis.DoesNotReturnIf(false)] bool condition, string message)
        {
            if (!condition)
            {
                throw new System.InvalidOperationException(message);
            }
        }

        // verify(cond, message, arg0[, arg1...]) -- the variadic context form. The AngelScript `throw` appends
        // each context value on its own "\n- <value>" line; this reproduces that layout so logs read identically.
        public static void Verify([System.Diagnostics.CodeAnalysis.DoesNotReturnIf(false)] bool condition, string message,
                                  params object?[] args)
        {
            if (!condition)
            {
                throw new System.InvalidOperationException(BuildMessage(message, args));
            }
        }

        // verify(x != null, message) narrowing form: returns the value typed non-null so the C# nullable-flow
        // analysis treats it as live afterward (honoring the repo's zero-warning rule on nullable references).
        // `[NotNull]` narrows the *argument* too, so a caller that ignores the return value still gets the
        // narrowing -- otherwise only the returned copy would be known non-null.
        public static T VerifyNotNull<T>([System.Diagnostics.CodeAnalysis.NotNull] T? value, string message)
            where T : class
        {
            if (value == null)
            {
                throw new System.InvalidOperationException(message);
            }

            return value;
        }

        public static void RunScriptGC()
        {
            System.GC.Collect();
            System.GC.WaitForPendingFinalizers();
            System.GC.Collect();
        }

        private static string BuildMessage(string message, object?[] args)
        {
            if (args == null || args.Length == 0)
            {
                return message;
            }

            var builder = new System.Text.StringBuilder(message);

            for (int i = 0; i < args.Length; i++)
            {
                builder.Append("\n- ");
                builder.Append(args[i]?.ToString() ?? "null");
            }

            return builder.ToString();
        }
    }
}
