# CMake initial cache

if( NOT DEFINED "ENV{FO_SOURCE}" )
	message( FATAL_ERROR "Define FO_SOURCE" )
endif()
if( NOT DEFINED "ENV{ANDROID_NDK}" )
	message( FATAL_ERROR "Define ANDROID_NDK" )
endif()

set( CMAKE_TOOLCHAIN_FILE "$ENV{FO_SOURCE}/BuildScripts/android.toolchain.cmake" CACHE PATH "" FORCE )
set( ANDROID YES CACHE PATH "" FORCE )
set( ANDROID_NDK $ENV{ANDROID_NDK} CACHE PATH "" FORCE )
set( ANDROID_ABI $ENV{ANDROID_ABI} CACHE PATH "" FORCE )
set( ANDROID_NATIVE_API_LEVEL "android-15" CACHE PATH "" FORCE )
set( ANDROID_STL "gnustl_static" CACHE PATH "" FORCE )
set( ANDROID_STL_FORCE_FEATURES OFF CACHE PATH "" FORCE )
