# CMake initial cache

if( NOT DEFINED "ENV{ROOT_FULL_PATH}" )
	message( FATAL_ERROR "Define ROOT_FULL_PATH" )
endif()
if( NOT DEFINED "ENV{ANDROID_NDK}" )
	message( FATAL_ERROR "Define ANDROID_NDK" )
endif()

set( CMAKE_TOOLCHAIN_FILE "$ENV{ROOT_FULL_PATH}/BuildScripts/android.toolchain.cmake" CACHE PATH "" FORCE )
set( CMAKE_MAKE_PROGRAM "make" CACHE PATH "" FORCE )
set( ANDROID YES CACHE STRING "" FORCE )
set( ANDROID_NDK $ENV{ANDROID_NDK} CACHE STRING "" FORCE )
set( ANDROID_ABI $ENV{ANDROID_ABI} CACHE STRING "" FORCE )
set( ANDROID_NATIVE_API_LEVEL "android-19" CACHE STRING "" FORCE )
set( ANDROID_STL "gnustl_static" CACHE STRING "" FORCE )
set( ANDROID_STL_FORCE_FEATURES OFF CACHE STRING "" FORCE )
