# CMake initial cache

set( CMAKE_SYSTEM_NAME "Linux" CACHE PATH "" FORCE )
set( CMAKE_C_FLAGS "-m32" CACHE PATH "" FORCE )
set( CMAKE_CXX_FLAGS "-m32" CACHE PATH "" FORCE )
set( HAVE_POLL_FINE_EXITCODE 0 CACHE STRING "" FORCE )
