# CMake initial cache

set( CMAKE_SYSTEM_NAME "Linux" CACHE STRING "" FORCE )
set( CMAKE_SYSTEM_PROCESSOR "i386" CACHE STRING "" FORCE )
set( CMAKE_C_FLAGS "-m32" CACHE STRING "" FORCE )
set( CMAKE_CXX_FLAGS "-m32" CACHE STRING "" FORCE )
set( HAVE_POLL_FINE_EXITCODE 0 CACHE STRING "" FORCE )
